version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - desafio-dois
    volumes:
      - ./node:/usr/src/app
    command: node index.js
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-dois

  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - "8080:80"
    networks:
      - desafio-dois
    depends_on:
      - app

networks:
  desafio-dois:
    driver: bridge
